name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry==1.8.3
      - name: Install deps
        working-directory: app/backend
        run: poetry install
      - name: Lint & typecheck
        working-directory: app/backend
        run: poetry run ruff check . && poetry run black --check . && poetry run mypy app
      - name: Tests
        working-directory: app/backend
        run: poetry run pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install PNPM
        run: corepack enable && corepack prepare pnpm@9.7.1 --activate
      - name: Install deps
        working-directory: app/frontend
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: app/frontend
        run: pnpm build



